.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,16 +33,18 @@ jobs:
         fi
 
         echo "Pulling Flyway Docker image..."
-        docker pull flyway/flyway
+        docker pull flyway/flyway || { echo "Failed to pull Flyway Docker image"; exit 1; }
 
-        echo "Running Flyway migrations..."        
-        docker run --rm -v $(pwd)/migrations:/flyway/sql flyway/flyway migrate \
-        -url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
-        -user=${{ secrets.DB_USER }} \
-        -password=${{ secrets.DB_PASSWORD }}
+        echo "Running Flyway migrations..."
+        docker run --rm \
+          -v $(pwd)/migrations:/flyway/sql \
+          flyway/flyway migrate -X \
+          -url=${DB_URL} \
+          -user=${DB_USER} \
+          -password=${DB_PASSWORD} \
+          || { echo "Flyway migration failed"; exit 1; }
 
         echo "Migrations completed successfully."
-          }        
 
     ### Этот шаг оставьте без изменений
     - name: Download and setup autotests binaries
